definitions:
  controllers.APIResponse:
    properties:
      data:
        $ref: '#/definitions/controllers.Data'
      error:
        $ref: '#/definitions/controllers.Error'
    type: object
  controllers.Data:
    properties:
      events:
        items:
          $ref: '#/definitions/controllers.EventResponse'
        type: array
    type: object
  controllers.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  controllers.EventResponse:
    properties:
      end_date:
        type: string
      end_time:
        type: string
      id:
        type: integer
      max_price:
        type: number
      min_price:
        type: number
      start_date:
        type: string
      start_time:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /search:
    get:
      consumes:
      - application/json
      description: Search events by date range
      parameters:
      - description: Start date
        in: query
        name: starts_at
        required: true
        type: string
      - description: End date
        in: query
        name: ends_at
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.APIResponse'
      summary: Search events
      tags:
      - events
swagger: "2.0"
